### ISSUE TITLE
FYI: Site’s not working

### ISSUE THREAD

**Issue by aarongustafson** [mydesignbuddy/otto-books-10kapart2016#1]
http://ottobooks-10kapart2016.azurewebsites.net/

**Comment by mydesignbuddy** [comment]
Hi Aaron,

Thanks for getting my entry. Sorry you had found an issue after deploying it. I'm not exactly sure how I can debug this but I figure I can try deploying the site on a test instants and see if I had the issue too. I created a new azure website and deployed the node app to it and it worked http://ottobooks-test.azurewebsites.net/. 

These are the setups I used when I deployed my instant and seem to work without any issue (I used Azure CLI on Mac):
1.  `azure config mode asm`
2. `azure login` (did the token login thing in the browser)
3. `azure site create --git ottobooks-test`
4. `git push azure master`
5. Open http://ottobooks-test.azurewebsites.net/ and site looks good.

I didn't change any code because I already had the iisnode.yml, package.json, and config/config.js setup to work with azure. I didn't change any env variables either.

I hate saying it :( "works on my machine" but I can't replicate the 404 issue. When I was developing it I was regularly deploying to my http://ottobooks.azurewebsites.net/ instants and that one is working too. I created the new test instants fresh in case I might have done something and removed it from my packages file later but it doesn't seem the be the issue. 

Please let me know if I can do anything else because I have been working really hard on this entry and I would hate to see it not make it in the contest.

Thank you so much,
Buddy Toups

**Comment by aarongustafson** [comment]
Gonna loop in @molant in case he can help…

**Comment by mydesignbuddy** [comment]
Ok cool thx

**Comment by molant** [comment]
@mydesignbuddy I'll take a deeper look later but are you building something before publishing? We only get the content in this repo + npm install so if there is anything else it should be committed in the repo unless you want to deal with changing the kudu deployment script which is a lot of trial and error :(

**Comment by mydesignbuddy** [comment]
I do minify js and css with grunt but I already committed the built assets.
I ran into that issue when developing but made sure the include the latest
grunt built files min.js and min.css.

Thanks

**Comment by molant** [comment]
@mydesignbuddy @aarongustafson I'm testing what could be wrong and I'm completely lost. It doesn't find any controllers,  that's why it is returning 404, but I don't know why :/
I've tried locally (works), normalizing the path, syncing again the code, etc. but it still doesn't work.

**Comment by molant** [comment]
@mydesignbuddy @aarongustafson fixed. Looks like it was an issue with node itself. Updated it to 6.6.0 and it is working now.

**Comment by mydesignbuddy** [comment]
@molant @aarongustafson awesome work thank you so much

**Comment by mydesignbuddy** [comment]
@aarongustafson is evertyping OK with my entry? Have heard are seen it on the 10kapart gallery. Let me know if you have any issues
